console.log('🔗 Stripe Dashboard Direct Links');
console.log('================================');
console.log('');
console.log('✅ PAYMENTS LIST (ye wala use karo):');
console.log('https://dashboard.stripe.com/test/payments');
console.log('');
console.log('✅ ALL ACTIVITY:');
console.log('https://dashboard.stripe.com/test/balance/overview');
console.log('');
console.log('✅ CUSTOMERS:');
console.log('https://dashboard.stripe.com/test/customers');
console.log('');
console.log('✅ SUBSCRIPTIONS:');
console.log('https://dashboard.stripe.com/test/subscriptions');
console.log('');
console.log('📋 Recent Payment IDs to search:');
console.log('- pi_3TEYDSD5YDWEPfCd16q7pmHW (Latest test payment)');
console.log('- pi_3TEH9BD5YDWEPfCd08xeK7x1 (£2000 subscription)');
console.log('- pi_3TEH6rD5YDWEPfCd1diTB1TD (£180 trial payment)');
console.log('');
console.log('💡 Tip: Ctrl+F kar ke payment ID search karo');